// <auto-generated />
using AppraisalAppV1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppraisalAppV1.Migrations
{
    [DbContext(typeof(AppraisalContext))]
    [Migration("20250825041816_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Appraisal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("AnalyticalAbility")
                        .HasColumnType("float");

                    b.Property<int?>("AppraisalYear")
                        .HasColumnType("int");

                    b.Property<string>("AppraiseeNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AttachmentFilePaths")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Communication")
                        .HasColumnType("float");

                    b.Property<double?>("CompanyPhilosophy")
                        .HasColumnType("float");

                    b.Property<double?>("Creativity")
                        .HasColumnType("float");

                    b.Property<double?>("CumulativeWeightage")
                        .HasColumnType("float");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Dependability")
                        .HasColumnType("float");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeAppraiseeNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Initiative")
                        .HasColumnType("float");

                    b.Property<double?>("JobKnowledge")
                        .HasColumnType("float");

                    b.Property<double?>("Judgement")
                        .HasColumnType("float");

                    b.Property<double?>("Leadership")
                        .HasColumnType("float");

                    b.Property<string>("MainTrainingAssignment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("NewIdeas")
                        .HasColumnType("float");

                    b.Property<double?>("OrganizingWork")
                        .HasColumnType("float");

                    b.Property<string>("PeriodCoveredFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ProblemAnalysis")
                        .HasColumnType("float");

                    b.Property<double?>("QualityOfWork")
                        .HasColumnType("float");

                    b.Property<double?>("QuantityOfWork")
                        .HasColumnType("float");

                    b.Property<string>("Ranking")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("RelationshipJunior")
                        .HasColumnType("float");

                    b.Property<double?>("RelationshipSenior")
                        .HasColumnType("float");

                    b.Property<string>("RequestDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("SafetyConsciousness")
                        .HasColumnType("float");

                    b.Property<double?>("SelfDevelopment")
                        .HasColumnType("float");

                    b.Property<string>("TrainingPlanned")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("WorkingUnderPressure")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeAppraiseeNumber");

                    b.ToTable("Appraisals");
                });

            modelBuilder.Entity("AppraisalAppV1.Models.Employee", b =>
                {
                    b.Property<string>("AppraiseeNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeriodCoveredFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AppraiseeNumber");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("AppraisalAppV1.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Appraisal", b =>
                {
                    b.HasOne("AppraisalAppV1.Models.Employee", null)
                        .WithMany("Appraisals")
                        .HasForeignKey("EmployeeAppraiseeNumber");
                });

            modelBuilder.Entity("AppraisalAppV1.Models.Employee", b =>
                {
                    b.Navigation("Appraisals");
                });
#pragma warning restore 612, 618
        }
    }
}
