// <auto-generated />
using AppraisalAppV1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppraisalAppV1.Migrations
{
    [DbContext(typeof(AppraisalContext))]
    partial class AppraisalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Appraisal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("AnalyticalAbility")
                        .HasColumnType("float");

                    b.Property<int?>("AppraisalYear")
                        .HasColumnType("int");

                    b.Property<string>("AppraiseeNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ApprovalStatusId")
                        .HasColumnType("int");

                    b.Property<string>("AttachmentFilePaths")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Communication")
                        .HasColumnType("float");

                    b.Property<double?>("CompanyPhilosophy")
                        .HasColumnType("float");

                    b.Property<double?>("Creativity")
                        .HasColumnType("float");

                    b.Property<double?>("CumulativeWeightage")
                        .HasColumnType("float");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Dependability")
                        .HasColumnType("float");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeAppraiseeNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Initiative")
                        .HasColumnType("float");

                    b.Property<double?>("JobKnowledge")
                        .HasColumnType("float");

                    b.Property<double?>("Judgement")
                        .HasColumnType("float");

                    b.Property<double?>("Leadership")
                        .HasColumnType("float");

                    b.Property<string>("MainTrainingAssignment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("NewIdeas")
                        .HasColumnType("float");

                    b.Property<double?>("OrganizingWork")
                        .HasColumnType("float");

                    b.Property<string>("PeriodCoveredFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ProblemAnalysis")
                        .HasColumnType("float");

                    b.Property<double?>("QualityOfWork")
                        .HasColumnType("float");

                    b.Property<double?>("QuantityOfWork")
                        .HasColumnType("float");

                    b.Property<string>("Ranking")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("RelationshipJunior")
                        .HasColumnType("float");

                    b.Property<double?>("RelationshipSenior")
                        .HasColumnType("float");

                    b.Property<string>("RequestDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("SafetyConsciousness")
                        .HasColumnType("float");

                    b.Property<double?>("SelfDevelopment")
                        .HasColumnType("float");

                    b.Property<int?>("SubmitterId")
                        .HasColumnType("int");

                    b.Property<string>("TrainingPlanned")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<double?>("WorkingUnderPressure")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AppraiseeNumber");

                    b.HasIndex("ApprovalStatusId");

                    b.HasIndex("EmployeeAppraiseeNumber");

                    b.HasIndex("SubmitterId");

                    b.HasIndex("UserId");

                    b.ToTable("Appraisals");
                });

            modelBuilder.Entity("AppraisalAppV1.Models.AppraisalAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppraisalId")
                        .HasColumnType("int");

                    b.Property<string>("ReviewerComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TaskAssigned")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppraisalId");

                    b.HasIndex("UserId");

                    b.ToTable("AppraisalAssignments");
                });

            modelBuilder.Entity("AppraisalAppV1.Models.Employee", b =>
                {
                    b.Property<string>("AppraiseeNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeriodCoveredFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AppraiseeNumber");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ApprovalStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CurrentActionerUserId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentStage")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalStages")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ApprovalStatus");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppraiseeNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppraiseeNumber");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Appraisal", b =>
                {
                    b.HasOne("AppraisalAppV1.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("AppraiseeNumber")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ApprovalStatus", "ApprovalStatus")
                        .WithMany()
                        .HasForeignKey("ApprovalStatusId");

                    b.HasOne("AppraisalAppV1.Models.Employee", null)
                        .WithMany("Appraisals")
                        .HasForeignKey("EmployeeAppraiseeNumber");

                    b.HasOne("User", "Submitter")
                        .WithMany()
                        .HasForeignKey("SubmitterId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("User", null)
                        .WithMany("Appraisals")
                        .HasForeignKey("UserId");

                    b.Navigation("ApprovalStatus");

                    b.Navigation("Employee");

                    b.Navigation("Submitter");
                });

            modelBuilder.Entity("AppraisalAppV1.Models.AppraisalAssignment", b =>
                {
                    b.HasOne("Appraisal", "Appraisal")
                        .WithMany("AppraisalAssignments")
                        .HasForeignKey("AppraisalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany("AppraisalAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appraisal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.HasOne("AppraisalAppV1.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("AppraiseeNumber")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Appraisal", b =>
                {
                    b.Navigation("AppraisalAssignments");
                });

            modelBuilder.Entity("AppraisalAppV1.Models.Employee", b =>
                {
                    b.Navigation("Appraisals");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("AppraisalAssignments");

                    b.Navigation("Appraisals");
                });
#pragma warning restore 612, 618
        }
    }
}
